set_property PACKAGE_PIN P5 [get_ports {x_in[4]}]
set_property PACKAGE_PIN P4 [get_ports {x_in[3]}]
set_property PACKAGE_PIN P3 [get_ports {x_in[2]}]
set_property PACKAGE_PIN P2 [get_ports {x_in[1]}]
set_property PACKAGE_PIN R2 [get_ports {x_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports y_out]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN F6 [get_ports y_out]
set_property CLOCK DEDICATED ROUTE FALSE [get_nets {clk IBUF}]